[build]
publish = "."

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/panini-custom"
  to = "/panini-custom.html"
  status = 200

[[redirects]]
  from = "/home.html"
  to = "/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301
  force = true
